### ISSUE TITLE
9008刷机失败

### ISSUE THREAD

**Issue by aimmarc** [LarrysGIT/Root_TB371FC#1]
![000](https://github.com/LarrysGIT/Root_TB371FC/assets/25717239/54df9563-d4bf-4f5d-90a6-25b319d03231)

你好，按照教程9008刷机，一直报错失败，请问是什么原因？

**Comment by LarrysGIT** [comment]
我之前遇到的是sahara protocol下面的错误
`Unable to read packet header. Only read 0 bytes`
你日志里有上面的条目吗？你的截图显示的是错误总结，具体错误应该要往上拉一些。

如果是和我一样的话，我最后用了两个方法之后刷成功了，
 - Load xml在弹出来的文件选择中选中所有xml文件，然后会又一弹一次，再一次选中所有xml文件。
 - 断开USB并关机，直到准备好按"Download"之前，再按住音量+连上USB，出现9008设备后马上点"Download"

**Comment by aimmarc** [comment]
是刷机工具不对，不能直接使用https://qfiltool.com下载的QFIL，要用QPST安装目录下的QFIL进行烧录才行。

**Comment by soyo136** [comment]
我一开始也是刷不过，用了QPST安装目录下的QFIL去烧录也不行，后面按照[LarrysGIT]的方法，能刷过了，但是不开机了。。。

**Comment by soyo136** [comment]
[LarrysGIT]的方法很有效，但是切记要解锁后才能刷
