### ISSUE TITLE
后续更新问题

### ISSUE THREAD

**Issue by mengrank** [LarrysGIT/Root_TB371FC#2]
使用该教程成功由405升到440，完成后系统会直接推送650，选择下载更新后会卡在正在安装
![Screenshot_20240526-132730](https://github.com/LarrysGIT/Root_TB371FC/assets/123852003/0fa1d104-ffed-49c3-8480-fee997fde2be)

**Comment by mengrank** [comment]
猜测是由于440到650隔了几个小版本，在等待一个办小时后安装成功，再次感谢大佬的收集的资源和教程

**Comment by zeromake** [comment]
@mengrank 我看教程如果刷过 boot.img（root），需要刷回原版 boot.img 才能 OTA 升级，但是这样就没有 OTA 后的 boot.img 文件 Magisk 应该就不能用了？这个是指要 OTA 升级就要放弃 root 吧。
