### ISSUE TITLE
刷机后不开机

### ISSUE THREAD

**Issue by soyo136** [LarrysGIT/Root_TB371FC#7]
刷完后平板重启，显示联想log后，提示设备损坏，无法启动，
![image](https://github.com/user-attachments/assets/6a3077f3-39ea-482b-b879-d9d72c875178)

过一会儿平板重启，进入查看SN的模式
![image](https://github.com/user-attachments/assets/0a7189c1-7982-4d33-bbcc-42bb86cffbc3)

附件是log，请帮忙看下是什么问题
[133765087693926840.log](https://github.com/user-attachments/files/17818646/133765087693926840.log)

**Comment by soyo136** [comment]
另外说明一下，我没有解锁BL，还有我刷机前版本是ZUI16，是否跟高版本降级有关系呢，还能进入9008模式再次刷机，不知道刷16的能否正常开机，可惜没有16的固件，如果谁有能分享给我，感激不尽！

**Comment by LarrysGIT** [comment]
https://ota-cdn.lenovo.com/firmware/2024828185240998-6800.zip 这是16.0.430的完整ROM
good luck

**Comment by soyo136** [comment]
首先感谢你的热心，但是这个OTA ROM对我好像没有帮助，我的pad已经无法正常开机进入系统，应该只能通过9008的方式去刷机了

**Comment by soyo136** [comment]
已解决，解锁后重新刷固件就正常开机了，感谢大家

**Comment by chaoscreater** [comment]
It's weird that we need to unlock the bootloader in order to flash via EDL mode. What's the point of this mode if you can just unlock bootloader and flash using Fastboot?

**Comment by chaoscreater** [comment]
> [ota-cdn.lenovo.com/firmware/2024828185240998-6800.zip](https://ota-cdn.lenovo.com/firmware/2024828185240998-6800.zip) 这是16.0.430的完整ROM good luck

@LarrysGIT how did you find this? Is there a page where we can check the latest OTA download?
